const aumbla = {
    name: "Bink Starlek",
    class: "Ranger",
    subclass: "Beast Master",
    level: 3,
    pb: 2,
    alignment: 'Lawful good',
    proficiencies: {
        armor: ['Light', 'medium', 'shields'],
        weapons: ['simple', 'martial'],
        mastery: [],
        tools: ['Cook'],
        languages: ['common', 'dwarvish', 'giant', 'gnomish', 'goblin'],
        saving: ['dex', 'wis'],
        skills: ['history', 'survival', 'animal', 'nature', 'perception', 'medicine'],
        expertise: ['animal']
    },
    race: 'Human (alt)',
    size: 'Medium',
    speed: 30,
    background: 'Fisher',
    gold: 8,
    silver: 0,
    copper: 0,
    hit_dice: 10,
    hp: 0,
    armor: 1,
    str: 9,
    dex: 16,
    con: 11 + 1,
    int: 11 + 1,
    wis: 15 + 1,
    cha: 9,
    feat: [
        {name: "", val: ""},
        {name: "", val: ""},
        {name: "", val: ""},
        {name: "Deft Explorer", val: "Choose one of your skill proficiencies (animal handeling). Your proficiency bonus is doubled for any ability check you make using the chosen skill. You can also speak, read, and write 2 additional languages of your choice. (gnomish, goblin)"},
        {name: "Primeval Awareness", val: "Beginning at 3rd level, you can use your action and expend one ranger spell slot to focus your awareness on the region around you. For 1 minute per level of the spell slot you expend, you can sense whether the following types of creatures are present within 1 mile of you (or within up to 6 miles if you are in your favored terrain): aberrations, celestials, dragons, elementals, fey, fiends, and undead. This feature doesn’t reveal the creatures’ location or number."},
        {name: "Two-Weapon Fighting", val: "When you engage in two-weapon fighting, you can add your ability modifier to the damage of the second attack."},
        {name: "Favored Enemy - Beast", val: "Beginning at 1st level, you have significant experience studying, tracking, hunting, and even talking to a certain type of enemy. \nChoose a type of favored enemy: aberrations, beasts, celestials, constructs, dragons, elementals, fey, fiends, giants, monstrosities, oozes, plants, or undead. Alternatively, you can select two races of humanoid (such as gnolls and orcs) as favored enemies. \nYou have advantage on Wisdom (Survival) checks to track your favored enemies, as well as on Intelligence checks to recall information about them. \nWhen you gain this feature, you also learn one language of your choice that is spoken by your favored enemies, if they speak one at all. \nYou choose one additional favored enemy, as well as an associated language, at 6th and 14th level. As you gain levels, your choices should reflect the types of monsters you have encountered on your adventures."},
        {name: "Chef", val: "Increase your Constitution or Wisdom score by 1, to a maximum of 20. \nYou gain proficiency with cook’s utensils if you don’t already have it. \nAs part of a short rest, you can cook special food, provided you have ingredients and cook's utensils on hand. You can prepare enough of this food for a number of creatures equal to 4 + your proficiency bonus. At the end of the short rest, any creature who eats the food and spends one or more Hit Dice to regain hit points regains an extra 1d8 hit points. \nWith one hour of work or when you finish a long rest, you can cook a number of treats equal to your proficiency bonus. These special treats last 8 hours after being made. A creature can use a bonus action to eat one of those treats to gain temporary hit points equal to your proficiency bonus."},
        {name: "Harvest the Water", val: "You gain advantage on ability checks made using fishing tackle. If you have access to a body of water that sustains marine life, you can maintain a moderate lifestyle while working as a fisher, and you can catch enough food to feed yourself and up to ten other people each day."},
    ],
    spells: {
        slots: [3],
        prepared: [],
        cantrips: [],
        lv1: [
            {
                name: "Hunter's Mark",
                casting_time: '1 bonus action',
                range: '90 feet',
                components: ['v'],
                duration: 'Concentration, up to 1 hour',
                val: "You choose a creature you can see within range and mystically mark it as your quarry. Until the spell ends, you deal an extra 1d6 damage to the target whenever you hit it with a weapon attack, and you have advantage on any Wisdom (Perception) or Wisdom (Survival) check you make to find it. \nIf the target drops to 0 hit points before this spell ends, you can use a bonus action on a subsequent turn of yours to mark a new creature.",
                levels: "When you cast this spell using a spell slot of 3rd or 4th level, you can maintain your concentration on the spell for up to 8 hours. When you use a spell slot of 5th level or higher, you can maintain your concentration on the spell for up to 24 hours."
            },
            {
                name: 'Animal Friendship',
                casting_time: '1 action',
                range: '30 feet',
                components: ['v', 's', 'm'],
                duration: '24 hours',
                val: "Target a Beast that you can see within range. The target must succeed on a Wisdom saving throw or have the Charmed condition for the duration. If you or one of your allies deals damage to the target, the spells ends. \nUsing a Higher-Level Spell Slot. You can target one additional Beast for each spell slot level above 1.",
            },
            {
                name: "Alarm",
                casting_time: '1 min or Ritual',
                range: '30 feet',
                components: ['v, s, m'],
                duration: '8 hour',
                val: "You set an alarm against intrusion. Choose a door, a window, or an area within range that is no larger than a 20-foot Cube. Until the spell ends, an alarm alerts you whenever a creature touches or enters the warded area. When you cast the spell, you can designate creatures that won’t set off the alarm. You also choose whether the alarm is audible or mental: \nAudible Alarm. The alarm produces the sound of a handbell for 10 seconds within 60 feet of the warded area. \nMental Alarm. You are alerted by a mental ping if you are within 1 mile of the warded area. This ping awakens you if you’re asleep.",
            },
            {
                name: "Detect Magic",
                casting_time: '1 action or ritual',
                range: 'self',
                components: ['v s'],
                duration: 'Concentration, up to 10 min',
                val: "For the duration, you sense the presence of magical effects within 30 feet of yourself. If you sense such effects, you can take the Magic action to see a faint aura around any visible creature or object in the area that bears the magic, and if an effect was created by a spell, you learn the spell's school of magic. \nThe spell is blocked by 1 foot of stone, dirt, or wood; 1 inch of metal; or a thin sheet of lead.",
            },
            {
                name: "Cure Wounds",
                casting_time: '1 action',
                range: 'Touch',
                components: ['v s'],
                duration: 'instantaneous',
                val: "A creature you touch regains a number of Hit Points equal to 2d8 plus your spellcasting ability modifier. \nUsing a Higher-Level Spell Slot. The healing increases by 2d8 for each spell slot level above 1.",
            },
        ],
        lv2: [],
        lv3: [],
        lv4: [],
        lv5: [],
        lv6: [],
        lv7: [],
        lv8: [],
        lv9: [],
        lv10: [],
        option: []
    },
    equipment: [
        {name: "Whip", val: "1d4 Slashing. Finesse, Reach, (slow)"},        
        {name: "Longbow", val: "1d8 piercing. Ammunition, range (150/600), heavy, two-Handed"},
        {name: "Arrows x2", val: ""},
        {name: "explorer's pack", val: "Includes a backpack, a bedroll, a mess kit, a tinderbox, 10 torches, 10 days of rations, and a waterskin. The pack also has 50 feet of hempen rope strapped to the side of it."},
        {name: "Shortsword x2", val: "1d6 piercing. Finesse, light"},
        {name: "Leather armor", val: "+1 to AC"},
        {name: "Fishing tackle", val: ""},
        {name: "Fishing net", val: ""},
        {name: "Fishing lure", val: "Looks like a human finger"},
        {name: "Travel Clothes", val: ""},
    ],
    familiar: {
        name: "Aumbla",
        ac: 10,
        hp: 15,
        speed: "30 feet",
        pb: 2,
        str: 18,
        dex: 10,
        con: 14,
        int: 2,
        wis: 10,
        cha: 4,
        skills: [],
        senses: "Passive Perseption 10",
        languages: "",
        traits: [
            {name: "Charge", val: "If the cow moves at least 20 feet straight toward a target and then hits it with a gore attack on the same turn, the target takes an extra 7 (2d6) piercing damage."}
        ],
        actions: [
            {name: "Gore", val: "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 7 (1d6 + 4) piercing damage."}
        ]
    },
    story: {
        intro: "",
        background: "",
        personality: "",
        features: ""
    }

}

export default aumbla